### PR TITLE
Add Paste Deployment

### PR DESCRIPTION
**Pull request by tswicegood**
Thanks to @amotzkau for this code.

### CODE REVIEW

**Comment by tswicegood** [comment]
@amotzkau, can you take a quick gander at this and make sure everything works for you still?  I don't have Paste setup locally to verify it.  I swapped out the `ini` syntax for the pure Python syntax for the entry point, but I'm pretty sure that they do the same thing.  Thanks!!

**Comment by tswicegood** [comment]
This supersedes #1.

**Comment by amotzkau** [comment]
Still works for me, thanks!

**Comment by tswicegood** [comment]
Released as v2.1.0!  :tada:  Thanks, @amotzkau!!

**Pull request merged**
